theme: jekyll-theme-minimal
title: Matti Mäki-Kihniä
description: Mobile software engineer, mainly focusing on Android but now and then on iOS as well. I am currently spending my time between studying at Aalto University and with developing the Android app of ePassi Payments Oy.  
show_downloads: "false"
logo: imgs/profile_picture.png
